# Generated by Django 5.2.6 on 2025-12-19 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uzytkownik',
            name='profile_image',
            field=models.TextField(default='https://freesvg.org/img/abstract-user-flat-4.png'),
        ),
    ]
