# Generated by Django 5.2.8 on 2025-11-30 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='ArticleId',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='CourseId',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='quizz',
            old_name='QuizzId',
            new_name='id',
        ),
    ]
