# Generated by Django 5.2.7 on 2025-11-08 18:04

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('ArticleId', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('wholeContent', models.JSONField(default=main.models.article_content_structure)),
            ],
        ),
    ]
