# Generated by Django 5.2.6 on 2025-12-21 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_uzytkownik_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='difficulty_level',
            field=models.CharField(default='easy', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='points',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='difficulty_level',
            field=models.CharField(default='easy', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='points',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quizz',
            name='difficulty_level',
            field=models.CharField(default='easy', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quizz',
            name='points',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uzytkownik',
            name='collected_points',
            field=models.IntegerField(default=0),
        ),
    ]
