# Generated by Django 5.2.6 on 2025-09-17 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_wpis_file_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('ArticleId', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('topic', models.CharField(max_length=20)),
                ('subject', models.CharField(max_length=20)),
                ('description', models.JSONField()),
                ('created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('TaskId', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('topic', models.CharField(max_length=20)),
                ('subject', models.CharField(max_length=20)),
                ('description', models.JSONField()),
                ('created', models.DateField(auto_now_add=True)),
                ('answer', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='uzytkownik',
            name='id_uzytkownika',
        ),
        migrations.RemoveField(
            model_name='uzytkownik',
            name='is_teacher',
        ),
        migrations.AddField(
            model_name='uzytkownik',
            name='UserId',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='uzytkownik',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.AlterField(
            model_name='uzytkownik',
            name='lname',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='uzytkownik',
            name='username',
            field=models.CharField(max_length=15),
        ),
        migrations.DeleteModel(
            name='User_Wpis',
        ),
        migrations.DeleteModel(
            name='Wpis',
        ),
    ]
