# Generated by Django 5.2.8 on 2025-12-01 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_articleid_article_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='id',
            new_name='ArticleId',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='id',
            new_name='CourseId',
        ),
        migrations.RenameField(
            model_name='quizz',
            old_name='id',
            new_name='QuizzId',
        ),
    ]
