# Generated by Django 5.2.6 on 2025-12-21 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_article_difficulty_level_article_points_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uzytkownik',
            name='daily_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='uzytkownik',
            name='weekly_points',
            field=models.IntegerField(default=0),
        ),
    ]
