# Generated by Django 5.2.6 on 2025-12-02 17:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_id_article_articleid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uzytkownik',
            name='email',
            field=models.EmailField(max_length=50, unique=True, validators=[django.core.validators.EmailValidator(code='', message='Invalid email')]),
        ),
    ]
