# Generated by Django 5.2.6 on 2025-09-17 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_article_task_remove_uzytkownik_id_uzytkownika_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='topic',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='topic',
            field=models.CharField(max_length=50),
        ),
    ]
