# Generated by Django 5.2.8 on 2025-11-13 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_article_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('CourseId', models.BigAutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('question', models.TextField()),
                ('answers', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Quizz',
            fields=[
                ('QuizzId', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=500)),
                ('link', models.URLField()),
                ('category', models.CharField(max_length=50)),
            ],
        ),
    ]
